[custom.all.graph]
type   = "local"
path   = "."
ipkg   = "graph.ipkg"
test   = "test/test.ipkg"

[custom.all.graph-test]
type   = "local"
path   = "test"
ipkg   = "test.ipkg"

[custom.all.graph-profile]
type   = "local"
path   = "profile"
ipkg   = "profile.ipkg"

[custom.all.algebra]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-algebra"
commit = "latest:main"
ipkg   = "algebra.ipkg"
